# Generated by Django 5.0.3 on 2024-03-13 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online_payment", "Online Payment"),
                            ("mpesa", "M-PESA"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=100,
                    ),
                ),
                (
                    "payment_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("pending", "Pending"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "rent_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rent_payments",
                        to="tenants.rentproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rent Payment",
                "verbose_name_plural": "Rent Payments",
            },
        ),
    ]
