# Generated by Django 5.0.3 on 2024-03-10 16:49

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "property",
            "0008_property_number_available_alter_property_bathrooms_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "identification_number",
                    models.CharField(
                        help_text="This is the identification number of the tenant",
                        max_length=8,
                        unique=True,
                        verbose_name="id_no",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Teacher", "Teacher"),
                            ("Engineer", "Engineer"),
                            ("Doctor", "Doctor"),
                            ("Artist", "Artist"),
                            ("Business Owner", "Business Owner"),
                            ("Freelancer", "Freelancer"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=100,
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
            },
        ),
        migrations.CreateModel(
            name="RentProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_in_date", models.DateField()),
                ("lease_start_date", models.DateField()),
                ("lease_end_date", models.DateField()),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payment_frequency",
                    models.CharField(default="NOT AVAILABLE", max_length=50),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, default="NOT AVAILABLE"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_rented",
                        to="property.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_renting_property",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rent Property",
                "verbose_name_plural": "Rent Properties",
            },
        ),
    ]
