# Generated by Django 5.0.2 on 2024-03-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "price",
                    models.IntegerField(
                        choices=[(10000, "Low"), (30000, "Normal"), (50000, "High")]
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        choices=[(1, "1 Bedroom"), (2, "2 Bedrooms"), (3, "3 Bedrooms")]
                    ),
                ),
                (
                    "bathrooms",
                    models.IntegerField(
                        choices=[
                            (1, "1 Bathroom"),
                            (2, "2 Bathrooms"),
                            (3, "3 Bathrooms"),
                        ]
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
