# Generated by Django 5.0.2 on 2024-03-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "Property", "verbose_name_plural": "Properties"},
        ),
    ]
