# Generated by Django 5.0.2 on 2024-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_alter_property_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="is_published",
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(
                choices=[("1 Bathroom", 1), ("2 Bathrooms", 2), ("3 Bathrooms", 3)]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(
                choices=[("1 Bedroom", 1), ("2 Bedrooms", 2), ("3 Bedrooms", 3)]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.IntegerField(
                choices=[("Low", 10000), ("Normal", 30000), ("High", 50000)]
            ),
        ),
    ]
