# Generated by Django 5.0.2 on 2024-03-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_remove_property_is_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Miscellaneous", "Miscellaneous"),
                        ],
                        default="Residential",
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property type",
                "verbose_name_plural": "Property types",
            },
        ),
        migrations.RemoveField(
            model_name="property",
            name="title",
        ),
        migrations.AddField(
            model_name="property",
            name="name",
            field=models.CharField(
                blank=True,
                default="NOT AVAILABLE",
                max_length=1000,
                null=True,
                verbose_name="property_name",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(
                choices=[(1, "1 Bathroom"), (2, "2 Bathrooms"), (3, "3 Bathrooms")]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(
                choices=[(1, "1 Bedroom"), (2, "2 Bedrooms"), (3, "3 Bedrooms")]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(
                blank=True, default="NOT AVAILABLE", max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.IntegerField(
                choices=[(10000, "Low"), (30000, "Normal"), (50000, "High")]
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property",
                to="property.propertytype",
            ),
        ),
    ]
