# Generated by Django 5.0.2 on 2024-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_propertytype_remove_property_title_property_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertytype",
            name="name",
            field=models.CharField(
                blank=True, default="NOT AVAILABLE", max_length=15, null=True
            ),
        ),
    ]
