# Generated by Django 5.0.2 on 2024-03-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_alter_propertytype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(
                choices=[
                    (0, "Single Room"),
                    (1, "1 Bathroom"),
                    (2, "2 Bathrooms"),
                    (3, "3 Bathrooms"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(
                choices=[
                    (0, "Single Room"),
                    (1, "1 Bedroom"),
                    (2, "2 Bedrooms"),
                    (3, "3 Bedrooms"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(
                blank=True,
                default="NOT AVAILABLE",
                max_length=1000,
                null=True,
                verbose_name="property name",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.IntegerField(
                choices=[
                    (5000, "Sh. 5000"),
                    (10000, "Sh. 10,000"),
                    (30000, "Sh. 30000"),
                    (50000, "Sh. 50000"),
                ]
            ),
        ),
    ]
