# Generated by Django 5.0.2 on 2024-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_alter_property_bathrooms_alter_property_bedrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(
                blank=True, default="NOT AVAILABLE", max_length=1000, null=True
            ),
        ),
    ]
