# Generated by Django 5.0.3 on 2024-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_alter_property_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="number_available",
            field=models.PositiveIntegerField(
                default=0,
                help_text="This is the number of property available",
                verbose_name="properties available",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(
                choices=[
                    (0, "0 Bedroom"),
                    (1, "1 Bathroom"),
                    (2, "2 Bathrooms"),
                    (3, "3 Bathrooms"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(
                choices=[
                    (0, "0 Bedroom"),
                    (1, "1 Bedroom"),
                    (2, "2 Bedrooms"),
                    (3, "3 Bedrooms"),
                ]
            ),
        ),
    ]
