# Generated by Django 5.0.2 on 2024-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_alter_property_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="number_available",
            field=models.PositiveIntegerField(
                default=0,
                help_text="This is the number of property available",
                verbose_name="properties available",
            ),
        ),
    ]
